version: '3.8'

services:
  # バックエンド API サーバー
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=production
      - PORT=8000
    networks:
      - kidscode-network
    command: npm start

  # フロントエンド本番サーバー
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "80:80"
    environment:
      - VITE_API_URL=https://kidscode-studio-backend.onrender.com
    depends_on:
      - backend
    networks:
      - kidscode-network

networks:
  kidscode-network:
    driver: bridge
